apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: antibots
  name: perimeterx-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: perimeterx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  namespace: antibots
  name: perimeterx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: perimeterx
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      namespace: antibots
      labels:
        app: perimeterx
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: antibots
      containers:
        - name: perimeterx
          image: registry.digitalocean.com/athenabot/antibots/perimeterx:latest
          ports:
            - containerPort: 3000
